[build]
  functions = "netlify/functions"

[dev]
  targetPort = 3000  # Set this to the port your app is using

[[redirects]]
  from = "/api/table"
  to = "/.netlify/functions/table"
  status = 200
  force = true
