[build]
  functions = "netlify/functions"

[dev]
  targetPort = 3000  # Set this to the port your app is using

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/jsonserver/jsonserver"
  status = 200
  force = true
